/** Central Florida + corridor cities for address autocomplete */
export const FLORIDA_CITIES = [
  "Altamonte Springs",
  "Apopka",
  "Auburndale",
  "Bartow",
  "Belle Isle",
  "Casselberry",
  "Celebration",
  "Clermont",
  "Cocoa",
  "Cocoa Beach",
  "Davenport",
  "Daytona Beach",
  "Debary",
  "Deland",
  "Deltona",
  "Dunedin",
  "Eustis",
  "Florida City",
  "Fort Meade",
  "Frostproof",
  "Geneva",
  "Groveland",
  "Haines City",
  "Holly Hill",
  "Howey-in-the-Hills",
  "Jacksonville",
  "Kissimmee",
  "Lady Lake",
  "Lake Mary",
  "Lakeland",
  "Leesburg",
  "Longwood",
  "Maitland",
  "Melbourne",
  "Minneola",
  "Mount Dora",
  "New Smyrna Beach",
  "Ocala",
  "Ocoee",
  "Orange City",
  "Orlando",
  "Ormond Beach",
  "Oviedo",
  "Palm Bay",
  "Palm Coast",
  "Poinciana",
  "Port Orange",
  "Saint Augustine",
  "Saint Cloud",
  "Sanford",
  "Sarasota",
  "Sebring",
  "Tampa",
  "Tavares",
  "Titusville",
  "Umatilla",
  "Winter Garden",
  "Winter Haven",
  "Winter Park",
  "Winter Springs",
  "Zephyrhills",
].sort((a, b) => a.localeCompare(b));

export function filterCities(query, limit = 8) {
  const q = (query || "").trim().toLowerCase();
  if (!q) return FLORIDA_CITIES.slice(0, limit);
  return FLORIDA_CITIES.filter((c) => c.toLowerCase().includes(q)).slice(
    0,
    limit,
  );
}
