/** Single source of truth for brand + NAP + SEO. */
export const SITE = {
  /** Public brand (DBA) */
  name: "FenceLine Florida",
  shortName: "FenceLine",
  /** Web / domain brand used in titles & search */
  webName: "FenceLine Florida",
  domain: "fencelineflorida.com",
  /** Registered legal entity */
  legalName: "Diler Dynamics Group LLC",
  /** One-line legal disclosure for footers & contracts */
  legalLine: "FenceLine Florida is a DBA of Diler Dynamics Group LLC.",
  /** Brand promise */
  tagline: "Straight lines. Strong fences.",
  /** Market / area line */
  marketLine: "Strong fences from Jacksonville to Tampa",
  /**
   * Primary meta description (~155–160 chars).
   * Derived from official company description.
   */
  description:
    "FenceLine Florida — professional fence install & repair across Central & North Florida. Wood, vinyl, aluminum & chain link. Jax to Tampa. Free quotes.",
  /**
   * Full official about / AEO description (on-page + schema).
   */
  about:
    "FenceLine Florida is a DBA of Diler Dynamics Group LLC, providing professional fence installation and repair services across Central and North Florida. We specialize in wood, vinyl, aluminum, and chain-link fencing for both residential and commercial properties, serving areas from Jacksonville to Tampa, including Orlando, Sanford, Kissimmee, Clermont, Lakeland, Daytona Beach, Melbourne, and Ocala. All installations are engineered for Florida’s soil and storm conditions, with properly set posts to ensure durability and longevity. We also manage permitting and HOA documentation as part of a seamless, full-service experience.",
  /** Second paragraph highlights for structured reuse */
  aboutEngineering:
    "All installations are engineered for Florida’s soil and storm conditions, with properly set posts to ensure durability and longevity. We also manage permitting and HOA documentation as part of a seamless, full-service experience.",
  url: "https://fencelineflorida.com",
  phone: "(407) 555-0198",
  phoneHref: "tel:+14075550198",
  smsHref:
    "sms:+14075550198?&body=Hi%20FenceLine%20Florida%20%E2%80%94%20I%27d%20like%20a%20free%20fence%20quote.",
  email: "hello@fencelineflorida.com",
  emailHref: "mailto:hello@fencelineflorida.com",
  address: {
    street: "1420 West Pine Street",
    city: "Orlando",
    region: "FL",
    postalCode: "32805",
    country: "US",
  },
  addressLine: "1420 West Pine Street, Orlando, FL 32805",
  mapsHref:
    "https://www.google.com/maps/search/?api=1&query=Orlando+FL+fence+company",
  geo: {
    latitude: 28.5383,
    longitude: -81.3792,
  },
  area: "Central & North Florida · Jacksonville to Tampa",
  serviceAreas: [
    "Jacksonville",
    "Orlando",
    "Tampa",
    "Sanford",
    "Kissimmee",
    "Clermont",
    "Lakeland",
    "Daytona Beach",
    "Melbourne",
    "Ocala",
    "Central Florida",
    "North Florida",
  ],
  year: new Date().getFullYear(),
  /**
   * Social share card — generated by app/opengraph-image.jsx (1200×630).
   * Optional logo asset: public/logo/og-logo.png
   */
  ogImage: "/opengraph-image",
  logo: "/logo/logo-dark.svg",
  /** Drop final logo here for share card + future header use */
  ogLogoPath: "/logo/og-logo.png",
  /** Core keywords for meta + schema */
  keywords: [
    "fence installation Central Florida",
    "fence installation North Florida",
    "fence repair Florida",
    "fence company Orlando",
    "fence company Jacksonville",
    "fence company Tampa",
    "wood fence installation",
    "vinyl fence installation",
    "aluminum fence",
    "chain link fence",
    "HOA fence permit",
    "storm fence repair Florida",
    "FenceLine Florida",
    "Diler Dynamics Group LLC",
    "fencelineflorida.com",
  ],
  /** Clean monochrome + forest green accent */
  colors: {
    black: "#111111",
    ink: "#111111",
    accent: "#1F6B4A",
    accentSoft: "#E8F2EC",
    gray: "#6B6B6B",
    line: "#E5E5E5",
    soft: "#F7F7F5",
    white: "#FFFFFF",
  },
};

export const HOME_TITLE =
  "Fence Installation & Repair Central Florida | FenceLine Florida";

export const HOME_DESCRIPTION = SITE.description;
